### PR TITLE
package: resolve #1, express version incompatible

### LINKED ISSUE #1: Express version too high
You were using `express` ~`3.0.0`, so to get this working I just used `"express": "^3.21.2",
`

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by dcousens** [comment]
ping @stevemcquaid

**Comment by stevemcquaid** [comment]
Hello. Sorry didn't even realize this

**Comment by stevemcquaid** [comment]
Have you confirmed the ability to run flawlessly with this change?

**Comment by dcousens** [comment]
I used it to fly a Parrot drone a few weeks back :+1:,  but,  you have a few wild cards in there so there is still things up to chance depending on when someone installs this.

**Comment by dcousens** [comment]
ping @stevemcquaid ,  what do you want to do with this PR?

**Comment by stevemcquaid** [comment]
Id like to be able to verify this working. Would you mind adding the rest of the version pinning? (I wasn't able to get it to run with this change)

**Comment by dcousens** [comment]
@stevemcquaid updated and tested locally:

**Comment by stevemcquaid** [comment]
Thanks so much for doing all of this! Merging now

**Pull request merged**
